#!/usr/bin/env python3
"""Generate the immutable Swift catalog and native gesture fixture from reviewed data."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
levels = json.loads((ROOT / "Data/challenges.json").read_text(encoding="utf-8"))
assert len(levels) == 20 and [v["id"] for v in levels] == list(range(101, 121))
assert all(v["parMoves"] == len(v["solution"]) for v in levels)
payload = "\n".join(json.dumps(v, separators=(",", ":")) + ("," if i < 19 else "") for i, v in enumerate(levels))
source = '''// Generated by scripts/generate_challenges.py from Data/challenges.json.
// Boards are fixed; exact gesture targets were certified offline. See Docs/CHALLENGE-DESIGN.md.
import Foundation

public enum ChallengeCatalog {
    public static let count = 20
    public static func number(for levelID: Int) -> Int? {
        (101...120).contains(levelID) ? levelID - 100 : nil
    }
    public static func level(id: Int) -> Level? {
        guard let number = number(for: id) else { return nil }
        return levels[number - 1]
    }
    public static func tierName(for levelID: Int) -> String {
        guard let number = number(for: levelID) else { return "Challenge Voyage" }
        return ["Crosscurrents", "Tight Waters", "Deep Strategy", "Master Harbour"][(number - 1) / 5]
    }
    public static let levels: [Level] = {
        do { return try JSONDecoder().decode([Level].self, from: Data(catalogJSON.utf8)) }
        catch { preconditionFailure("Invalid bundled challenge catalog: \\(error)") }
    }()
    private static let catalogJSON = #"""
[
''' + payload + '''
]
"""#
}
'''
(ROOT / "Sources/PrismCore/ChallengeCatalog.swift").write_text(source, encoding="utf-8")
first = levels[0]
fixture = '''// Generated from the shipped first challenge; native UI tests perform real drag gestures.
enum ChallengeFixtures {
    static let firstTitle = ''' + json.dumps(first["title"]) + '''
    static let pieces: [Int: (width: Int, height: Int, cellX: Int, cellY: Int)] = [
'''
for p in first["pieces"]:
    cells = p["cells"]
    fixture += f'        {p["id"]}: ({max(c["x"] for c in cells)+1}, {max(c["y"] for c in cells)+1}, {cells[0]["x"]}, {cells[0]["y"]}),\n'
fixture += '    ]\n    static let solution: [(pieceID: Int, dx: Int, dy: Int, steps: Int)] = [\n'
deltas = {"up": (0,-1), "right": (1,0), "down": (0,1), "left": (-1,0)}
for move in first["solution"]:
    dx, dy = deltas[move["direction"]]
    fixture += f'        ({move["pieceID"]}, {dx}, {dy}, {move["steps"]}),\n'
fixture += '    ]\n}\n'
(ROOT / "UITests/ChallengeFixtures.swift").write_text(fixture, encoding="utf-8")
print(f"Generated {len(levels)} fixed challenges and {len(first['solution'])} UI gestures")
