#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p artifacts
xcodebuild -version > artifacts/xcode-version.txt
xcodebuild build-for-testing \
  -project RiseBake.xcodeproj \
  -scheme RiseBake \
  -configuration Debug \
  -sdk iphonesimulator \
  -destination 'generic/platform=iOS Simulator' \
  -derivedDataPath build \
  ARCHS="$(uname -m)" ONLY_ACTIVE_ARCH=NO \
  CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
  2>&1 | tee artifacts/xcodebuild.log
app_path="$PWD/build/Build/Products/Debug-iphonesimulator/RiseBake.app"
test -x "$app_path/RiseBake"
# Verify architecture and platform before uploading anything.
lipo -info "$app_path/RiseBake" | tee artifacts/architecture.txt
xcrun vtool -show-build "$app_path/RiseBake" | tee artifacts/platform.txt
python3 - <<'PY'
from pathlib import Path
import platform
assert platform.machine() in Path('artifacts/architecture.txt').read_text(), 'Missing host simulator architecture'
assert 'IOSSIMULATOR' in Path('artifacts/platform.txt').read_text(), 'This is not a simulator build'
PY
# Boot an available iPhone, launch the actual app and keep a real screenshot artifact.
xcrun simctl list devices available --json > build/simulators.json
simulator_id="$(python3 - <<'PY'
import json,os
s=json.load(open('build/simulators.json'))
wanted=os.environ.get('RISEBAKE_SIMULATOR_RUNTIME')
phones=[d for key,devices in sorted(s['devices'].items(),reverse=True) if 'iOS' in key and (not wanted or key==wanted) for d in devices if d.get('isAvailable') and d['name'].startswith('iPhone')]
if not phones:raise SystemExit('No iPhone simulator is installed on this Xcode image')
print(phones[0]['udid'])
PY
)"
trap 'xcrun simctl shutdown "$simulator_id" >/dev/null 2>&1 || true' EXIT
xcrun simctl boot "$simulator_id" || true
python3 - "$simulator_id" <<'PYBOOT'
import subprocess,sys
subprocess.run(['xcrun','simctl','bootstatus',sys.argv[1],'-b'],check=True,timeout=300)
PYBOOT
xcrun simctl install "$simulator_id" "$app_path"
xcrun simctl launch "$simulator_id" com.risebake.preview | tee artifacts/simulator-launch.txt
sleep 4
# A second launch terminates the app only if still running; check the process first.
xcrun simctl spawn "$simulator_id" launchctl list > build/processes.txt
if ! grep -q 'com.risebake.preview' build/processes.txt; then
  echo 'RiseBake did not remain running after launch.'
  exit 1
fi
xcrun simctl io "$simulator_id" screenshot artifacts/RiseBake-iPhone.png
# Capture the actual native account screen independently of UI-test assertions.
xcrun simctl terminate "$simulator_id" com.risebake.preview
xcrun simctl launch "$simulator_id" com.risebake.preview --show-welcome
sleep 2
xcrun simctl io "$simulator_id" screenshot artifacts/RiseBake-sign-in.png
xcrun simctl terminate "$simulator_id" com.risebake.preview
# Appetize expects a zip whose root contains RiseBake.app (not an .ipa or source zip).
ditto -c -k --sequesterRsrc --keepParent "$app_path" artifacts/RiseBake-simulator.zip
python3 - <<'PY'
from zipfile import ZipFile
with ZipFile('artifacts/RiseBake-simulator.zip') as z:
    assert 'RiseBake.app/Info.plist' in z.namelist()
    assert 'RiseBake.app/RiseBake' in z.namelist()
print('Native simulator bundle is ready.')
PY

# Exercise persistent native navigation, a timer, theme selection and the basket.
set +e
xcodebuild test-without-building -project RiseBake.xcodeproj -scheme RiseBake \
  -configuration Debug -parallel-testing-enabled NO -test-timeouts-enabled YES -destination "platform=iOS Simulator,id=$simulator_id,arch=$(uname -m)" \
  -derivedDataPath build -resultBundlePath artifacts/RiseBake-UI.xcresult \
  ARCHS="$(uname -m)" ONLY_ACTIVE_ARCH=YES \
  CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
  2>&1 | tee artifacts/ui-tests.log
test_status=${PIPESTATUS[0]}
set -e
if [ -d artifacts/RiseBake-UI.xcresult ]; then
  xcrun xcresulttool export attachments --path artifacts/RiseBake-UI.xcresult --output-path artifacts/ui-screenshots || true
fi
# Keep PDFs generated by the same native renderer used by the shipped app.
data_container="$(xcrun simctl get_app_container "$simulator_id" com.risebake.preview data)"
if [ -d "$data_container/Documents/Receipt-QA" ]; then
  cp -R "$data_container/Documents/Receipt-QA" artifacts/receipt-qa
fi
exit "$test_status"
