"""Create curated, editable starter recipes and a clean first-install catalog."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
s=json.loads((root/'RiseBake/Resources/seed.json').read_text())
# Every quantity is for the recipe yield, with units preserved by batch scaling.
specs=[
('Sourdough Loaf','Breads',1,'loaf',[('Bread flour',500,'g'),('Water',350,'ml'),('Active sourdough starter',100,'g'),('Salt',10,'g')],[('Mix',20,None,'Mix flour and water, rest, then incorporate active starter and salt.'),('Bulk ferment',240,None,'Cover and ferment until aerated; fold gently every 30 minutes during the first two hours. Adjust for room temperature and dough activity.'),('Shape & proof',120,None,'Shape tightly and proof in a floured basket until the dough springs back slowly.'),('Bake',45,240,'Preheat a Dutch oven. Score and bake covered for 25 minutes, then uncovered until deeply golden.'),('Cool',60,None,'Cool fully on a rack before slicing.')]),
('Croissant','Pastries',12,'croissants',[('Bread flour',500,'g'),('Milk',280,'ml'),('Sugar',55,'g'),('Salt',10,'g'),('Instant yeast',7,'g'),('Butter for dough',40,'g'),('Butter for lamination',250,'g'),('Egg for glaze',1,'piece')],[('Mix dough',20,None,'Mix all dough ingredients except lamination butter and egg. Knead until smooth.'),('Chill',120,None,'Flatten, cover and chill the dough. Shape cold lamination butter into a square.'),('Laminate',90,None,'Enclose butter, roll and make three single folds, chilling 30 minutes between folds.'),('Shape & proof',120,None,'Cut triangles, roll loosely and proof until visibly puffy; keep cool enough that the butter does not melt.'),('Bake',22,200,'Brush with beaten egg and bake until deeply golden. Cool on a rack.')]),
('Berry Celebration Cake','Cakes',1,'cake',[('Plain flour',300,'g'),('Sugar',280,'g'),('Butter for sponge',200,'g'),('Eggs',4,'piece'),('Milk',200,'ml'),('Baking powder',12,'g'),('Vanilla',2,'tsp'),('Butter for frosting',200,'g'),('Icing sugar',400,'g'),('Mixed berries',200,'g')],[('Prepare batter',25,None,'Cream sponge butter and sugar. Beat in eggs and vanilla, then fold in flour, baking powder and milk.'),('Bake',30,175,'Divide between two lined 20 cm tins. Bake until set and a tester comes out clean.'),('Cool',60,None,'Cool layers completely before frosting.'),('Decorate',35,None,'Beat frosting butter and icing sugar until fluffy. Fill and cover the cake; top with washed, dry berries.')]),
('Morning Buns','Pastries',12,'buns',[('Bread flour',500,'g'),('Milk',250,'ml'),('Butter',100,'g'),('Sugar',60,'g'),('Egg',1,'piece'),('Instant yeast',7,'g'),('Salt',8,'g'),('Brown sugar for filling',120,'g'),('Cinnamon',2,'tbsp')],[('Mix',20,None,'Mix flour, milk, half the butter, sugar, egg, yeast and salt; knead until elastic.'),('Rise',90,None,'Cover and let rise until doubled.'),('Fill & shape',25,None,'Roll into a rectangle. Spread remaining softened butter, brown sugar and cinnamon. Roll up and cut 12 buns.'),('Proof',45,None,'Place in a lined tin with space to rise. Proof until puffy.'),('Bake',25,180,'Bake until golden, then cool slightly before serving.')]),
('Baguette','Breads',3,'baguettes',[('Bread flour',500,'g'),('Water',350,'ml'),('Salt',10,'g'),('Instant yeast',3,'g')],[('Mix',15,None,'Mix all ingredients to a shaggy dough and knead lightly.'),('Ferment',150,None,'Cover and ferment until airy, folding twice during the first hour.'),('Shape & proof',60,None,'Divide into three, shape gently into baguettes, and proof on floured linen.'),('Bake',25,240,'Score and bake in a preheated oven with steam until crisp and golden.'),('Cool',30,None,'Cool on a wire rack.')]),
('Chocolate Cake','Cakes',1,'cake',[('Plain flour',250,'g'),('Cocoa powder',70,'g'),('Sugar',300,'g'),('Baking powder',10,'g'),('Eggs',3,'piece'),('Milk',240,'ml'),('Vegetable oil',120,'ml'),('Dark chocolate',250,'g'),('Cream',250,'ml')],[('Mix',20,None,'Whisk flour, cocoa, sugar and baking powder. Mix eggs, milk and oil; combine with dry ingredients.'),('Bake',35,175,'Divide between two lined 20 cm tins; bake until set and a tester comes out clean.'),('Cool',60,None,'Cool the cake layers completely.'),('Ganache & finish',30,None,'Warm cream gently, pour over chopped chocolate and stir smooth. Cool to spreading consistency, then fill and cover.')]),
('Chocolate Chip Cookies','Cookies',12,'cookies',[('Plain flour',250,'g'),('Butter',150,'g'),('Brown sugar',140,'g'),('Egg',1,'piece'),('Chocolate chips',180,'g'),('Baking soda',0.5,'tsp'),('Salt',0.5,'tsp'),('Vanilla',1,'tsp')],[('Mix',15,None,'Cream butter and sugar, beat in egg and vanilla, then fold in dry ingredients and chocolate.'),('Chill',30,None,'Chill dough, then divide into 12 portions.'),('Bake',12,180,'Space on lined trays; bake until edges are golden and centers just set.'),('Cool',20,None,'Leave on trays for five minutes, then transfer to a rack.')]),
('Fudge Brownies','Brownies',16,'squares',[('Dark chocolate',200,'g'),('Butter',150,'g'),('Sugar',220,'g'),('Eggs',3,'piece'),('Plain flour',100,'g'),('Cocoa powder',25,'g'),('Salt',0.25,'tsp')],[('Mix',20,None,'Melt chocolate and butter gently. Whisk eggs and sugar, combine, then fold in flour, cocoa and salt.'),('Bake',25,175,'Spread into a lined 20 cm square tin and bake until the center is set but moist.'),('Cool & slice',90,None,'Cool completely before slicing into 16 squares.')]),
('Blueberry Muffins','Muffins',12,'muffins',[('Plain flour',300,'g'),('Sugar',150,'g'),('Baking powder',12,'g'),('Milk',240,'ml'),('Vegetable oil',100,'ml'),('Eggs',2,'piece'),('Blueberries',200,'g'),('Vanilla',1,'tsp')],[('Mix',15,None,'Combine dry ingredients. Whisk milk, oil, eggs and vanilla, fold together gently, then add berries.'),('Portion',10,None,'Divide between 12 paper-lined muffin cups.'),('Bake',23,190,'Bake until golden and a tester comes out clean.'),('Cool',20,None,'Cool five minutes in the tin, then move to a rack.')]),
('Vanilla Cupcakes','Cupcakes',12,'cupcakes',[('Plain flour',180,'g'),('Butter for sponge',125,'g'),('Sugar',150,'g'),('Eggs',2,'piece'),('Milk',100,'ml'),('Baking powder',6,'g'),('Vanilla',2,'tsp'),('Butter for icing',150,'g'),('Icing sugar',300,'g')],[('Mix',20,None,'Cream sponge butter and sugar, beat in eggs and vanilla, then fold in flour, baking powder and milk.'),('Bake',20,175,'Divide into 12 liners and bake until springy and a tester comes out clean.'),('Cool',40,None,'Cool completely on a rack.'),('Ice',20,None,'Whip icing butter and icing sugar with a little milk as needed; pipe onto cooled cakes.')]),
('Garden Focaccia','Breads',1,'tray',[('Bread flour',500,'g'),('Water',380,'ml'),('Olive oil',50,'ml'),('Instant yeast',7,'g'),('Salt',10,'g'),('Cherry tomatoes',150,'g'),('Rosemary',1,'tbsp')],[('Mix',15,None,'Mix flour, water, yeast, salt and half the oil into a wet dough.'),('Rise',120,None,'Cover and rise until bubbly, folding twice during the first hour.'),('Proof & top',60,None,'Spread into an oiled tray. Proof, then dimple with remaining oil and add tomatoes and rosemary.'),('Bake',25,220,'Bake until golden on top and cooked underneath. Cool on a rack.')]),
('Sesame Bagels','Breads',8,'bagels',[('Bread flour',500,'g'),('Water',290,'ml'),('Sugar',25,'g'),('Salt',10,'g'),('Instant yeast',7,'g'),('Sesame seeds',40,'g'),('Honey for boiling water',1,'tbsp')],[('Mix & knead',20,None,'Mix flour, water, sugar, salt and yeast; knead into a firm smooth dough.'),('Rise',60,None,'Cover and let rise until doubled.'),('Shape',20,None,'Divide into eight balls. Poke and stretch a wide hole through each.'),('Boil',10,None,'Bring a wide pan of water with honey to a simmer; boil bagels about 45 seconds on each side. Add sesame seeds.'),('Bake',22,220,'Bake on a lined tray until evenly golden, then cool.')]),
('Strawberry Tart','Tarts',1,'tart',[('Plain flour',250,'g'),('Butter',125,'g'),('Icing sugar',75,'g'),('Egg',1,'piece'),('Milk',400,'ml'),('Egg yolks',4,'piece'),('Sugar',80,'g'),('Cornstarch',35,'g'),('Vanilla',1,'tsp'),('Strawberries',400,'g')],[('Make pastry',20,None,'Rub butter into flour, add icing sugar and egg, bring together gently.'),('Chill',30,None,'Wrap and chill pastry before rolling into a 23 cm tart tin.'),('Bake shell',25,180,'Line with paper and weights; bake 15 minutes, remove weights and bake until golden.'),('Make custard',20,None,'Whisk yolks, sugar and cornstarch. Temper with warm milk, then cook while whisking until thick and bubbling; stir in vanilla.'),('Cool & assemble',90,None,'Cool shell and custard, fill, then arrange washed dry strawberries. Refrigerate until serving.')]),
('Pistachio Macarons','Macarons',20,'sandwiches',[('Almond flour',150,'g'),('Icing sugar',150,'g'),('Egg whites',110,'g'),('Caster sugar',150,'g'),('Butter',100,'g'),('Icing sugar for filling',150,'g'),('Pistachio paste',40,'g')],[('Make batter',30,None,'Sift almond flour and icing sugar. Whip whites, gradually adding caster sugar to stiff peaks. Fold in dry mix until batter flows slowly in ribbons.'),('Pipe & rest',45,None,'Pipe 40 rounds on lined trays, tap out bubbles and rest until tops are dry to touch.'),('Bake',16,150,'Bake one tray at a time until shells lift cleanly once cooled. Adjust for your oven.'),('Fill',40,None,'Cool shells fully. Beat filling butter, icing sugar and pistachio paste; sandwich matching shells.'),('Mature',1440,None,'Refrigerate in an airtight container overnight before serving.')]),
('Walnut Banana Bread','Cakes',1,'loaf',[('Ripe banana',300,'g'),('Plain flour',220,'g'),('Brown sugar',130,'g'),('Butter',100,'g'),('Eggs',2,'piece'),('Baking soda',1,'tsp'),('Walnuts',80,'g'),('Salt',0.25,'tsp')],[('Mix',20,None,'Mash banana, stir in melted cooled butter, sugar and eggs. Fold in flour, soda, salt and walnuts.'),('Bake',55,175,'Pour into a lined loaf tin and bake until a tester comes out clean.'),('Cool',45,None,'Cool ten minutes in the tin, then lift onto a rack.')]),
('Chocolate Éclairs','Pastries',12,'éclairs',[('Water',250,'ml'),('Butter',100,'g'),('Plain flour',150,'g'),('Eggs',4,'piece'),('Whipping cream',350,'ml'),('Icing sugar',40,'g'),('Dark chocolate',150,'g')],[('Make choux',25,None,'Bring water and butter to a boil. Stir in flour and cook until dough pulls away. Cool slightly, then beat in eggs gradually until glossy.'),('Pipe & bake',35,200,'Pipe 12 lengths. Bake until firm and golden; avoid opening the oven early.'),('Cool',40,None,'Pierce each shell to release steam and cool completely.'),('Fill & glaze',25,None,'Whip cream with icing sugar, fill shells, and dip tops into gently melted chocolate. Keep chilled.')])]
prices=[1200,450,12000,600,600,6500,350,400,425,450,1400,350,3200,250,1600,550]
for n,(name,cat,y,unit,ingredients,method) in enumerate(specs):
 if n>=len(s['products']): s['products'].append(dict(id=f'p{n}',name=name,category=cat,price=prices[n],cost=round(prices[n]*.3),capacity=48,image=n,unit='piece' if y>1 else unit,description=f'Handcrafted {name.lower()}, baked with care.',allergens='Wheat, dairy, eggs'+(', nuts' if n in [13,14] else ', sesame' if n==11 else ''),recipe={},steps=[x[0] for x in method]))
recipes=[]
for n,(name,cat,y,unit,ingredients,method) in enumerate(specs):
 recipes.append(dict(id=f'recipe-p{n}',productID=f'p{n}',name=name,yieldUnit=unit,**{'yield':y},ingredients=[dict(id=f'p{n}-i{i}',name=nm,amount=a,unit=u) for i,(nm,a,u) in enumerate(ingredients)],method=[dict(id=f'p{n}-s{i}',title=title,instruction=text,minutes=m,**({'temperatureC':t} if t else {})) for i,(title,m,t,text) in enumerate(method)],notes='Starter recipe — adjust the method, timings and yield to your kitchen.'))
s.update(version=2,day='2026-09-18',recipes=recipes,bakeSessions=[],customers=[],orders=[],recurring=[],tasks={},cart={},nextOrder=1001)
s['settings'].update(bakery='My Bakery',owner='Baker',background='flourGarden')
for i,allergens in {10:'Wheat / gluten',11:'Wheat, sesame',13:'Eggs, dairy, almonds, pistachios',14:'Wheat, dairy, eggs, walnuts'}.items(): s['products'][i]['allergens']=allergens
for dest in ['RiseBake/Resources/seed.json','Tests/RiseBakeCoreTests/catalog.json']:
 (root/dest).write_text(json.dumps(s,indent=2,ensure_ascii=False)+'\n')
